import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lista de tareas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
      <Toaster toastOptions={{
          style:{
            background: 'rgb(51 65 85)',
            color: '#fff'
          }
        }} />
        <div className='flex flex-col min-h-screen'>  
          <Navbar/> 
          {children}
        </div>
      </body>
    </html>
  );
}
